Repository sse-labs/fachproject-metrics-framework, pull requests merged in 2021-12, with the labels that each got.

#7 Added support for JMOD files
  src/main/scala/application/FileAnalysisApplication.scala
  src/main/scala/opal/OPALProjectHelper.scala
Labels: bug, enhancement, framework

#26 Add TypeAnalysis interface
  src/main/scala/analysis/TypeAnalysis.scala
Labels: framework

#28 Changed TypeAnalysis to ClassFileAnalysis
  src/main/scala/analysis/ClassFileAnalysis.scala
  src/main/scala/analysis/TypeAnalysis.scala
Labels: enhancement, framework

#31 Schnittstelle für Zugriff auf File Objekte
  src/main/scala/analysis/MultiFileAnalysis.scala
Labels: enhancement, framework

#29 Feature/#loop
  src/main/scala/impl/MultiFileAnalysisApplication.scala
  src/main/scala/impl/SingleFileAnalysisApplication.scala
  src/main/scala/impl/group5/NumberOfLoopsAnalysis.scala
  src/test/resources/group5/gson-2.8.9.jar
  src/test/resources/group5/h2-2.0.202.jar
  src/test/resources/group5/pdfbox-2.0.24.jar
  src/test/scala/impl/group5/NumberOfLoopsAnalysisTest.scala
Labels: enhancement, Group 5
