Repository sse-labs/fachproject-metrics-framework, pull requests merged in 2022-02, with the labels that each got.

#90 Add --evaluate-performance switch to produce performance report
  src/main/scala/ApplicationConfiguration.scala
  src/main/scala/application/ApplicationPerformanceStatistics.scala
  src/main/scala/application/FileAnalysisApplication.scala
  src/main/scala/application/MultiFileAnalysisApplication.scala
  src/main/scala/application/SingleFileAnalysisApplication.scala
  src/main/scala/input/CliParser.scala
  src/main/scala/output/CsvFileOutput.scala
  src/main/scala/output/StatisticsOutput.scala
  src/test/scala/testutils/AnalysisTestUtils.scala
Labels: enhancement, framework

#92 Add Assembly Plugin
  build.sbt
  project/plugins.sbt
  src/main/scala/impl/ApplicationEntryPoint.scala
Labels: bug, enhancement, framework

#93 Evaluation Feature and Assembly Plugin
  build.sbt
  project/plugins.sbt
  src/main/scala/ApplicationConfiguration.scala
  src/main/scala/application/ApplicationPerformanceStatistics.scala
  src/main/scala/application/FileAnalysisApplication.scala
  src/main/scala/application/MultiFileAnalysisApplication.scala
  src/main/scala/application/SingleFileAnalysisApplication.scala
  src/main/scala/impl/ApplicationEntryPoint.scala
  src/main/scala/input/CliParser.scala
  src/main/scala/output/CsvFileOutput.scala
  src/main/scala/output/StatisticsOutput.scala
  src/test/scala/testutils/AnalysisTestUtils.scala
Labels: enhancement, framework

#95 Fix ClassCastException in FanInAnalysis
  src/main/scala/impl/group2/FanInAnalysis.scala
Labels: bug, Group 2
